### ISSUE TITLE
Future releases

### ISSUE THREAD

**Issue by andrea-pellegrinelli-cgm** [EventStore/ClientAPI.NetCore#10]
Hello, I would like to know if someone is still working on this project and if there are planned other releases.
Thank you

**Comment by SvenEV** [comment]
I would also be interested

**Comment by jageall** [comment]
yes and yes. Releases for this project tend to follow after the releases of the main .NET client. There are not that many releases of the .NET client as it is fairly stable. There will be another release shortly to line up with 4.0.2 release of the server/client.
