### ISSUE TITLE
can't get a connection in core 2.0 console app

### ISSUE THREAD

**Issue by BoasE** [EventStore/ClientAPI.NetCore#17]
I've a .net core 2.0 console application. when i try to insert in the event store i always get the following error.

`System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred. (Connection 'ES-16f299cd-d67e-44db-a448-dffe87e79c70' was closed.)`

`EventStore.ClientAPI.Exceptions.ConnectionClosedException: 'Connection 'ES-c97c90c4-c464-44a4-87de-753a4818e52c' was closed.'`

I've code in non core applications targeting the same server  (localhost) and they get connected and events inserted.

I use the current released eventstore server and current nuget packages

My Code in the client looks like this:

            
```csharp
            var creds = new UserCredentials("admin","changeit");
            var settings = ConnectionSettings.Create()
                .SetDefaultUserCredentials(creds)
                .SetHeartbeatInterval(TimeSpan.FromSeconds(10))
                .Build();

            Stopwatch watch = Stopwatch.StartNew();
            IEventStoreConnection connection = EventStoreConnection.Create(settings, new IPEndPoint(IPAddress.Parse("127.0.0.1"), 113));
            await connection.ConnectAsync();

            var @event = new CustomerCreatedFromConsoleEvent();
            @event.Name = "foo";
            @event.Headers.Set(EventHeaderKeys.AggregateId, Guid.NewGuid().ToString());
            @event.Headers.Set(EventHeaderKeys.EventId, Guid.NewGuid().ToString());
            @event.Headers.Set(EventHeaderKeys.Created, DateTime.Now);
            var content = JsonConvert.SerializeObject(@event);
            
            var data = new EventData(Guid.NewGuid(),"foo",true,Encoding.UTF8.GetBytes( content),null);
            
            var result = await connection.AppendToStreamAsync("abc", -1, data);
```

Beside this error i can't see any connections on http://localhost:2113/web/index.html#/dashboard event after the ConnectAsync call.

**Comment by jageall** [comment]
If this is the actual code you are using the port is wrong, it should be 1113. after making that change and making up what the other classes look like, i have this code working locally.

**Comment by BoasE** [comment]
ok sorry maybe i just missed that. ill give it  a try

**Comment by jageall** [comment]
any update?

**Comment by BoasE** [comment]
hi yes it was my bad, i really made that bug in the port.

**Comment by pgermishuys** [comment]
Thanks for getting back to us @BoasE

**Comment by gregoryyoung** [comment]
21113 is the http port, you were likely also getting some interesting error messages from the node about malformed http requests :)
