### ISSUE TITLE
Embedded client

### ISSUE THREAD

**Issue by wegged** [EventStore/ClientAPI.NetCore#18]
Any thoughts on supporting EmbeddedClient for .NET standard 2.0?

**Comment by Kees-Schouten** [comment]
Any update on this? I'm looking for a EmbeddedClient .Net core/standard for a .net Core 2.0 project.

**Comment by yohanmishkin** [comment]
@jageall any thoughts on reasonable testing strategies for .net core code without the embedded client?

**Comment by iberodev** [comment]
Is that the only option we have to run integration tests against a "real" event store? I am assuming the recommendation would be to run EventStore.ClusterNode with the flag ` --mem-db`
I've never used Chocolatey to download/install servers, I am assuming it is similar to using docker and run an EventStore container when executing the tests?

I was investigating on how to integration test EventStore (I created a question in SO https://stackoverflow.com/questions/53688783/eventstore-integration-testing-with-in-memory-node) and I found this thread.

Is there any update on this support or a more detailed alternative for newbies?

**Comment by jen20** [comment]
As of version 5.0.0, Event Store's .NET Client API (in the main EventStore/EventStore repository) targets .NET Frameworks 4.5.2 and 4.6.0, and .NET Standard 2.0.0, and consequently this repository is being archived.

The embedded client does not yet work on .NET Core (it is contingent on making the server work with .NET Core, which is an ongoing effort). EventStore/EventStore#1716 tracks this going forward.
