### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by StevenBlair1** [EventStore/ClientAPI.NetCore#2]
Not sure if this is the best place to post but I have tried using the alpha driver on VS2015 and a clean install of VS2017 and I keep running into the same problem when I try to read events:

`System.IO.FileNotFoundException: 'Could not load file or assembly 'protobuf-net, Version=2.1.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67'. The system cannot find the file specified.'`

My references look like this:

![image](https://cloud.githubusercontent.com/assets/3097999/24374810/20d73f8a-132e-11e7-8e85-7172bbf26e69.png)

I have tried installing the nuget from Manage Nuget  Packages, as well as the command line and each time I get the same issue.

I have also tried manually installing this nuget (protobuf) but get the same error.

Anyone help?

**Comment by StevenBlair1** [comment]
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or ass
embly 'protobuf-net, Version=2.1.0.0, Culture=neutral, PublicKeyToken=257b51d87d
2e4d67'. The system cannot find the file specified.
   at EventStore.ClientAPI.Transport.Tcp.ProtobufExtensions.Serialize[T](T proto
Contract)
   at EventStore.ClientAPI.ClientOperations.OperationBase`2.CreateNetworkPackage
(Guid correlationId)
   at EventStore.ClientAPI.Internal.OperationsManager.ExecuteOperation(Operation
Item operation, TcpPackageConnection connection)
   at EventStore.ClientAPI.Internal.OperationsManager.TryScheduleWaitingOperatio
ns(TcpPackageConnection connection)
   at EventStore.ClientAPI.Internal.OperationsManager.CheckTimeoutsAndRetry(TcpP
ackageConnection connection)
   at EventStore.ClientAPI.Internal.EventStoreConnectionLogicHandler.TimerTick()

   at EventStore.ClientAPI.Internal.EventStoreConnectionLogicHandler.<.ctor>b__2
0_8(TimerTickMessage msg)
   at EventStore.ClientAPI.Internal.SimpleQueuedHandler.<>c__DisplayClass3_0`1.<
RegisterHandler>b__0(Message msg)
   at EventStore.ClientAPI.Internal.SimpleQueuedHandler.ProcessQueue(Object stat
e)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.
IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by pgermishuys** [comment]
@StevenBlair1 this is definitely the right place to be posting about this. This needs to be looked at.

**Comment by pgermishuys** [comment]
@StevenBlair1 @jageall might have some insights as to whether or not this will be fixed in the branch he is working on.

**Comment by StevenBlair123** [comment]
So Pieter, are you fairly certain this is a problem in the nuget?
I was worried it was my environment had become corrupted.

**Comment by pgermishuys** [comment]
@StevenBlair123 will have a look at it now.

**Comment by pgermishuys** [comment]
I performed the following steps
1. Created a new console application from within VS2017 which targets `.NETCoreApp 1.1`
2. Installed the EventStore.ClientAPI.NetCore nuget package
     e.g. 
    `install-package EventStore.ClientAPI.NetCore -version 0.0.1-alpha`
3. Connected to a local instance of Event Store and read a 100 events without an issue.

**Comment by StevenBlair123** [comment]
Hmmm, that is not good news for me.
I tried exactly the same thing (outside my main solution) and get the errors as stated above.
Even when I explicitly install that protobuf nuget into the project (and verify it's there in reference) it still complains it cannot find.
I tried this in a ASP.NET, Console and even class library.

**Comment by jageall** [comment]
I have not seen this issue with this package before either, i have several environments and several clients who are using this package and no one has reported this before. 
?
that said are you specifying which sdk you want to use in the global.json file for 2015? I have had issues when it hasn't been specified where things seemed to work fine until runtime.

```"sdk": { "version": "1.0.0-preview2-003131" }```

**Comment by StevenBlair123** [comment]
I am getting the same problem under VS2015 and VS2017

**Comment by jageall** [comment]
which release of .net core are you targeting?

**Comment by StevenBlair123** [comment]
1.1

**Comment by jageall** [comment]
I am not able to repro this here. can you share a minimum repro on github somewhere?

**Comment by StevenBlair123** [comment]
OK, I will detail the exact steps I am doing to get this issue (will be later today).
When the EventStore client is being used for reading back events, where would it be checking for the protobuf dll?
Maybe something on my system has become corrupted.

**Comment by jageall** [comment]
protobuf is used anytime the client sends messages over tcp, so as soon as
you call connectasync. it doesn't check for protobuf, the jit compiler will
only try and load it when it hits that code path, which will happen in any
normal usage of the client (except maybe projection management as that is
done over http)

**Comment by StevenBlair1** [comment]
I came home to replicate the issue for this Issue, and noticed the nuget is now 4.0.0-alpha-1.
Installed it and...

No problem!!!

It's working (reading and writing)

**Comment by jageall** [comment]
Hmm, no changes to the package manifest. Is that on a different machine?

**Comment by StevenBlair1** [comment]
Nope. Same PC. I literally just opened a new solution up to recreate the steps.
Went to add the nuget and noticed a new version available.

**Comment by StevenBlair1** [comment]
Oh wait :\
Just went back to my actual proper solution and updated the nuget.
Same problem in this solution.

**Comment by jageall** [comment]
I am pretty sure this is a problem with the way the solution was created / processed, but i suspect it to be a problem with the VS tooling rather than the package. if you have time, can you create a new solution the same way you created the one that works and add the original package and see if it still works? I suspect it will.

**Comment by StevenBlair1** [comment]
Yup, you are correct.
This is really weird.
I have now created a Console App and a ASP.NET inside the problem solution and both work.
Looking back at my ASP.NET entry point, there are a *lot* of things inside the .csproj compared to the working ASP.Net project.

I copied in the csproj from the working ASP.NET, overwriting the existing one, and it appears to work.

I wonder if one of these ItemGroup elements could have been causing a problem.

Just for reference:

```
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>FileProcessor</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>FileProcessor</PackageId>
    <RuntimeFrameworkVersion>1.1.1</RuntimeFrameworkVersion>
    <PackageTargetFallback>$(PackageTargetFallback);dotnet5.6</PackageTargetFallback>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EventStore.ClientAPI.NetCore" Version="0.0.1-alpha" />
    <PackageReference Include="Microsoft.CSharp" Version="4.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Formatters.Xml" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.1" />
    <PackageReference Include="System.Interactive.Async" Version="3.1.1" />

  </ItemGroup>
```

This was the previous version before tonight.

**Comment by jageall** [comment]
Closing as no further reports and issue appears to be fixed.
