### ISSUE TITLE
Support initializing ConnectionSettingsBuilder from Connection String 

### ISSUE THREAD

**Issue by ben-foster-cko** [EventStore/ClientAPI.NetCore#8]
Currently it's not possible to initialize a `ConnectionSettingsBuilder` from a connection string. This is quite limiting as it means we can't extend the settings passed from the connection string with extensions such as `UseConsoleLogger()` etc.

It is possible to use `ConnectionString.GetConnectionSettings(connectionString)` but the underlying properties (such as logger) are readonly at this point.

**Comment by jageall** [comment]
You can do this using the following code:

```C#
var builder = ConnectionSettings.Create().KeepReconnecting();
var settings = ConnectionString.GetConnectionSettings("ConnectTo=tcp://admin:changeit@localhost:1113; HeartBeatTimeout=500", builder);
var connection = EventStoreConnection.Create(settings);
```

does that help?

**Comment by jageall** [comment]
wait, i may have found a bug with this...

**Comment by jageall** [comment]
this is the correct syntax to use:
```

**Comment by jageall** [comment]
Closing this for now as the code provided above allows the use of connection string and builder together. feel free to reopen if you don't feel this solves your use case
