### ISSUE TITLE
persistent subscriptions with $ce-item can not resolve event

### ISSUE THREAD

**Issue by rm2k** [EventStore/ClientAPI.NetCore#9]
persistent subscriptions with `$ce-item` fails to resolve the event, I have 

    var streamName = $ce-item;
    var groupName = "test_group;
    var subscription = _conn.ConnectToPersistentSubscription(
                streamName,
                groupName,
                eventAppeared,
                subscriptionDropped,
                userCredentials);

Posting to `item-{id}`, my `eventAppeared` is hit with `resolvedEvent` having resolved data as:
    
    resolvedEvent.Event.Data = 0@item-{id} // this happens to be the event name on the web UI.
    resolvedEvent.Event.EventType = $> // I don't get what this means
    resolvedEvent.Event.IsJson = false // My data is json, I could confirm on the web UI

Changing to `CatchUpSubscriptions`, everything works fine.

**edit**:
Reproduced over [here](https://github.com/rm2k/GetEventStoreDemo).

**Comment by jageall** [comment]
That event is a linkTo event, you need to set resolveLinkTo to true in the subscription settings when you create it with PersistentSubscriptionSettings.Create().ResolveLinkTos() as it is false by default

**Comment by rm2k** [comment]
Thanks @jageall
